### ISSUE TITLE
Networking is required when using, which is not good

### ISSUE THREAD

**Issue by chainofhonor** [acecilia/OpenWRTInvasion#111]
使用的时候需要联网,这点比较不好
希望能把使用时需要下载的文件直接提前下载完毕,并集成到脚本里面,这样执行命令的时候就不需要访问外网了
由于众所周知的原因,中国的网络访问github会有问题
国内的恩山论坛已经有大量的网友因为网络问题而执行失败了
Networking is required when using, which is not good
It is hoped that the files to be downloaded during use can be directly downloaded in advance and integrated into the script, so that there is no need to access the Internet when executing the command
For well-known reasons, China's Internet access to GitHub will have problems
A large number of netizens have failed to implement the enshan forum in China because of network problems

**Comment by acecilia** [comment]
Feel free to open a pull request :)
