### ISSUE TITLE
hi, there are a encoding issue

### ISSUE THREAD

**Issue by NoString** [acecilia/OpenWRTInvasion#130]
I'm a chinese user, and when I run the remote_command_execution_vulnerability.py ,  I will show a error
`Router IP address: 192.168.31.1`
`stok: 64541fbba476852422ba63742d8f25e9`   
`Traceback (most recent call last):`   
  `File "C:\Users\zhs\Documents\OpenWRTInvasion-0.0.3\remote_command_execution_vulnerability.py", line 42, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
`
I tried to fix it, and success. this is the new code, 
for the 41 line:
`with open("speedtest_urls_template.xml","rt", encoding='utf-8') as f:` 
for the 45 line:
`with open("build/speedtest_urls.xml",'wt', encoding='utf-8') as f:`

**Comment by acecilia** [comment]
Thanks! Feel free to open a PR
