### ISSUE TITLE
[SUCCESS] Xiaomi Mi Router 4A Gigabit, all flawless using these commands

### ISSUE THREAD

**Issue by PieBru** [acecilia/OpenWRTInvasion#131]
Hi all, after searching here for similar issues I succeeded with what IMO is a repeatable solution to solve the AP/Repeater issues.

- Router model, reported on the label on the back: R4A
- Router firmware version: 3.0.24
- Bought on march 2022: https://www.amazon.it/gp/product/B07WDLJWQG/ (just for your reference, I'm not affiliated in any way)
- My PC: Arch Linux

1. Connected the 4A router WAN port to an uplink to the internet (actually an AP on my LAN).
2. Wired the 4A router LAN port to the ethernet port of my PC.
3. On a CLI window on my PC, executed this command: `watch 'sudo ifconfig enp3s0 192.168.31.2; ping -c 2 192.168.31.1`
4. Booted the 4a router.
5. On my PC, browsed http://192.168.31 to complete the initial setup wizard.
6. After the router reboot, executed these commands on my PC:

```
       $ cd somewhere
       $ git clone https://github.com/acecilia/OpenWRTInvasion
       $ cd OpenWRTInvasion
       $ wget https://downloads.openwrt.org/releases/21.02.2/targets/ramips/mt7621/openwrt-21.02.2-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin 
       $ mv openwrt-21.02.2-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin  firmware.bin
       $ curl https://downloads.openwrt.org/releases/21.02.2/targets/ramips/mt7621/sha256sums | grep gigabit
       **a5e2198b18b5207ac1c53e143f6c7b2c9616cc9dd245520eaf2997e0fc5cc9a6** *openwrt-21.02.2-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin
       $ python -m http.server       (on another CLI in the same directory)
       $ pip3 install -r requirements.txt
       $ python3 remote_command_execution_vulnerability.py
       $ telnet 192.168.31.1		user: root / passw: root
# Now we are on the 4A router CLI...
       root@XiaoQiang:/# cd /tmp
       root@XiaoQiang:/tmp# curl http://**192.168.31.<PC_IP>**:8000/firmware.bin --output firmware.bin
       root@XiaoQiang:/tmp# ./busybox sha256sum firmware.bin 
**a5e2198b18b5207ac1c53e143f6c7b2c9616cc9dd245520eaf2997e0fc5cc9a6**  firmware.bin
       mtd -e OS1 -r write firmware.bin OS1
```
The telnet CLI is on the routers LAN side, so the router IP address should be **192.168.31.1** and I configured the PC IP address as **192.168.31.2** using the command `watch "sudo ifconfig enp3s0 192.168.31.2; ping -c 2 192.168.31.1"` that, after the successful OpenWrt installation, becomes `watch "sudo ifconfig enp3s0 192.168.1.2; ping -c 2 192.168.1.1"`

This is the mtd command result:
![Screenshot from 2022-04-06 19-39-26](https://user-images.githubusercontent.com/6537434/162041956-eaaeef5d-ec94-4006-a0b6-fb723988166d.png)

And this is the captured flag :-)

![Screenshot from 2022-04-06 19-38-38](https://user-images.githubusercontent.com/6537434/162042026-c30b4a90-b567-4ccb-88a1-fc88d97ee360.png)

Hope this can be useful to someone.
Piero

**Comment by acecilia** [comment]
Awesome, thanks for the detailed explanation! 🙌 I am sure will be valuable
