### ISSUE TITLE
may be not work for ver.2.30.20?

### ISSUE THREAD

**Issue by yumusb** [acecilia/OpenWRTInvasion#135]
I had try it many times in chinese version 2.30.20.

**Comment by devidlis123** [comment]
Hello, mine is the same version. No solution?

**Comment by Iven-hoo** [comment]
i got the problem by printing out the code information. The problem is that the new version of 2.30.20 api interface has changed, and the parameters may have been adjusted

**Comment by acecilia** [comment]
Closing this as duplicate of https://github.com/acecilia/OpenWRTInvasion/issues/141
