### ISSUE TITLE
What to do with R4AG Chinese version firmware 2.30.20?

### ISSUE THREAD

**Issue by tangmingxing1988** [acecilia/OpenWRTInvasion#147]
I tried to upload stock firmware in this repository from the web UI, and the file can't pass the check.

So, anyway to upgrade or downgrade firmware to make this possible?

**Comment by acecilia** [comment]
Please do not open the same issue again and again. It is mentioned in the readme that `2.30.20` is not supported.
Please use the [main ticket](https://github.com/acecilia/OpenWRTInvasion/issues/141) if you want to continue discussion and explore other alternatives

**Comment by Mohamadreza1982** [comment]
2.30.500+any progress ? im ready  to use UART if somone helps me
