### ISSUE TITLE
[Fail] Mi Extender AC1200 (RA75)

### ISSUE THREAD

**Issue by nathanielcwm** [acecilia/OpenWRTInvasion#159]
Similar hardware to Mi Router 4a 100M 

[Relevant OpenWRT wiki page](https://openwrt.org/inbox/toh/xiaomi/mi_wifi_range_extender_ac1200_model_ra75)

[Relevant OpenWRT forum thread](https://forum.openwrt.org/t/almost-supported-xiaomi-ra75-aka-miwifi-range-extender-ac1200/134855)

**Comment by acecilia** [comment]
Thanks! Updated readme
