### ISSUE TITLE
[Success]v0.0.1 Tested working on Mi Router 4c Firmware version 2.14.92

### ISSUE THREAD

**Issue by Johnnybyzhang** [acecilia/OpenWRTInvasion#162]
I have tested on Mi Router 4c Firmware version 2.14.92 and the script worked flawlessly.
I used MacOS buildin Python3 and netcat

**Comment by acecilia** [comment]
Superb, thanks for reporting!

**Comment by CharonChy** [comment]
Why do I prompt "* Maybe your firmware version is not supported, please have a look at  https://github.com/acecilia/OpenWRTInvasion/blob/master/README.md#unsupported-routers-and-firmware-versions
* Anyway you can try it with: telnet 192.168.31.1"
 The configuration was successful, but ssh could not connect to the server
