### ISSUE TITLE
Cyberduck vs SCP

### ISSUE THREAD

**Issue by juancarlospdt** [acecilia/OpenWRTInvasion#167]
I like your job a lot, but i think as most of us use a UNIX env, and as you tell us at the beggining that Windows could be risky to use as it has compatibility problems, I wouldn't go for Cyberduck.

So you are on linux, and the git guide redirects you towards a windows tool. At that point, if you have SSH connection, you can simply download it, and SCP into the router as easy as it could, and with out the need of checking for a WIN environment.

PD: I suggest this myself because as i was following the git guide i got into the Cyberduck recomendation and i forgot (silly) that i could get the file no with an FTP but directly copying the file with SCP. Hope it helps

**Comment by acecilia** [comment]
The Cyberduck is just used as an example, as mentioned in the instructions. Cyberduck is not Windows exclusive, it supports also MacOS. There are other tools you can use. If you want to modify existing proposed tool, feel free to open a pull request
