### ISSUE TITLE
where can i find the indian rom for this router?

### ISSUE THREAD

**Issue by XDAGamer** [acecilia/OpenWRTInvasion#169]
so i bricked my router in process of forcing openwrt through telnet though it was not supported according to this github repository. Now the thing is im on on global rom and want the indian unit firmware, where can i find it?

**Comment by XDAGamer** [comment]
i have the gigabit version, v2 i think

**Comment by 410252889** [comment]
https://github.com/acecilia/OpenWRTInvasion/files/9920159/miwifi_r4av2_all_release_2.30.25.bin.zip

**Comment by XDAGamer** [comment]
not working actually i was mistaken only global version is working

**Comment by XDAGamer** [comment]
why has this been closed? i am not able to get the rom working

**Comment by acecilia** [comment]
Because this issue has no relation with this repository. This repository is hosting a tool to get access to the OS of the router. It is not hosting ROMs

**Comment by XDAGamer** [comment]
i might have v1 because this firmware is not working yet chinese and global are fine which both are v1 in my reckoning because it has similar name format but only thing they don't do is mention v2 in their name like this one
