### ISSUE TITLE
Couldn't unzip, the file is corrupt on v3.2.13 - mi router 4c

### ISSUE THREAD

**Issue by AddaxSoft** [acecilia/OpenWRTInvasion#174]
- Device firmware version: 3.2.13
- Device type 4c
- edition: global

I get this error on console:
```
start uploading config file ...
{"code":1629,"msg":"Couldn't unzip, the file is corrupt"}
start exec command...
{"download":0,"bandwidth":0,"code":0}
done!
```

**Comment by AddaxSoft** [comment]
the issue was using Windows WSL. Switching to Linux solved this.
I'm using legacy 0.0.1, so I wonder why WSL messes up the tar file for mi router firmware?

**Comment by acecilia** [comment]
Closing, as the issue got solved by switching to Linux
