### ISSUE TITLE
Instruction on windows or ubuntu

### ISSUE THREAD

**Issue by 1003199311** [acecilia/OpenWRTInvasion#18]
/usr/bin/nc - l 4444
Is use on macos
But many people use windows or linux,that command is not work on
Because I use Xiaomi 4Q ,I only can use v0.0.1

**Comment by acecilia** [comment]
I do not have a windows or linux machine, so i can not help you. It should be no problem to run it on linux, otherwise use mac inside a virtual machine

**Comment by acecilia** [comment]
For example, for ubuntu see: https://unixmen.com/play-with-netcat-in-ubuntu/

**Comment by acecilia** [comment]
Or you can use version `0.0.2` or `0.0.3`, you just need to change the busybox binary to use mips instead of mipsel: https://github.com/acecilia/OpenWRTInvasion/blob/master/script.sh#L17
