### ISSUE TITLE
How to permanently enable telnet or ssh

### ISSUE THREAD

**Issue by jinglei207** [acecilia/OpenWRTInvasion#19]
does anyone know how to permanently enable telnet or ssh even after a reboot?

**Comment by acecilia** [comment]
I do not think you can do that easily in the stock firmware. I would recommend to better ask in the [openWrt](https://forum.openwrt.org/t/xiaomi-mi-router-4a-gigabit-edition-r4ag-r4a-gigabit-fully-supported-and-flashable-with-openwrtinvasion/36685) forum

**Comment by acecilia** [comment]
https://forum.openwrt.org/t/xiaomi-mi-router-4a-gigabit-edition-r4ag-r4a-gigabit-fully-supported-and-flashable-with-openwrtinvasion/36685/857
