### ISSUE TITLE
Version 2 (Telnet) Works on Xiaomi Mi Router 3G v2 Version 2.28.217 (Flashed from Windows 10)

### ISSUE THREAD

**Issue by Diablofx** [acecilia/OpenWRTInvasion#24]
Works very well on this router.
Flashed from Windows Powershell without issue with version 2 (Telnet).
Couln't install Luci with release provided by you (Kernel version error).
Performed a sysupgrade with last snapshop from openwrt and then instalation of Luci went well.
Thanks a lot

**Comment by acecilia** [comment]
Thanks for the info :)
