### ISSUE TITLE
Solved : code 1629

### ISSUE THREAD

**Issue by Gooucky** [acecilia/OpenWRTInvasion#25]
First proposed on Issues 17, 20 May

I solved the problem several days later, but I didn't remember to record it on Github. Now for some reason, I have to access this project again, and I'll share how I solved it.

"code 1629 " is a debug feedback, normally operating as the project demonstrates, 1629 it won't appear.
But "code 1629 " is always there, it's a rewrite backup protection mechanism. As long as you use some debug measurement, it'll appear from the background.
So the problem I met has nothing to do with 1629.

The breakdown in this project comes from a China mainland network problem. And the breakdown won't emerge on aboard devices.
If you operate in China mainland, choose the 'Global' option on your ladder tools, and everything will be right.

![2020-08-16](https://user-images.githubusercontent.com/43288063/90334204-9738f100-dffe-11ea-8249-cf010edd363f.png)

**Comment by acecilia** [comment]
Thanks for the info :)
