### ISSUE TITLE
Use ssh tool install luci, can't connect network.

### ISSUE THREAD

**Issue by zy-zero** [acecilia/OpenWRTInvasion#28]
when I run opkg update, looks like can't connect network
it show me Faild to download the packege list ...
check your network settings and connectivity
![image](https://user-images.githubusercontent.com/23359848/91629567-a8213380-e9fc-11ea-805e-9b37ae311641.png)

And when I ping some host like www.baidu.com
it show me bad address.
![image](https://user-images.githubusercontent.com/23359848/91629575-bbcc9a00-e9fc-11ea-8690-5a0076ae32b3.png)

Here is my wan config:
![image](https://user-images.githubusercontent.com/23359848/91629596-e0c10d00-e9fc-11ea-9b8f-05387e883562.png)

Can you help me where I am wrong?

**Comment by acecilia** [comment]
No, I cant. I do not know anything about your network setup. The easier solution would be to simplify your network setup as much as possible: no VPNs, no custom configurations... just the basic router to the internet.

Please search for a solution on the OpenWrt forum (most probably somebody else has been through you problem), or ask there: https://forum.openwrt.org/t/xiaomi-mi-router-4a-gigabit-edition-r4ag-r4a-gigabit-fully-supported-and-flashable-with-openwrtinvasion

This is not an issue with the code in this repo: it is probably an issue with your network setup
