### ISSUE TITLE
能不能通过某种方式来把小米r3gv2升级开发版

### ISSUE THREAD

**Issue by haotian2004** [acecilia/OpenWRTInvasion#29]
比如说编译官方签名的固件，使其能绑定小米帐号下载ssh工具包

**Comment by haotian2004** [comment]
my English is not good

**Comment by acecilia** [comment]
I do not think what you are asking for is possible.

But this is not the right place to ask that kind of questions, please ask them in the OpenWrt forum: https://forum.openwrt.org/t/xiaomi-mi-router-4a-gigabit-edition-r4ag-r4a-gigabit-fully-supported-and-flashable-with-openwrtinvasion
