### ISSUE TITLE
tested on the AC2350 AIOT 

### ISSUE THREAD

**Issue by jww-cw** [acecilia/OpenWRTInvasion#46]
Unfortunately this did not work on the AC2350 AIOT  https://www.mi.com/global/mi-aiot-router-ac2350/

```
prime@ubuntu:/tmp/OpenWRTInvasion$ python3 remote_command_execution_vulnerability.py
Router IP address [press enter for using the default 192.168.31.1]: 192.168.1.131
stok: XXXXX
****************
router_ip_address: 192.168.1.131
stok: XXXXX
****************
start uploading config file...
start exec command...
done! Now you can connect to the router using several options: (user: root, password: root)
* telnet 192.168.1.131
* ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc -o UserKnownHostsFile=/dev/null root@192.168.1.131
* ftp: using a program like cyberduck
prime@ubuntu:/tmp/OpenWRTInvasion$ telnet 192.168.1.131
Trying 192.168.1.131...
telnet: Unable to connect to remote host: Connection refused
prime@ubuntu:/tmp/OpenWRTInvasion$ ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc -o UserKnownHostsFile=/dev/null root@192.168.1.131
ssh: connect to host 192.168.1.131 port 22: Connection refused
prime@ubuntu:/tmp/OpenWRTInvasion$
```

**Comment by jww-cw** [comment]
FW version "version":"3.0.36"

**Comment by acecilia** [comment]
Thanks for reporting it 👍 I will update the readme

**Comment by eisaev** [comment]
Unfortunately, so far on this model, the only working method requires a second access point with the ability to respond to an http request. I used what was at hand: a very old ASUS WL-500gP with Entware firmware and nginx. But on a router with OpenWRT, this is even easier. See details here: https://forum.openwrt.org/t/adding-openwrt-support-for-xiaomi-ax3600/55049/766

**Comment by dobosz23** [comment]
Good evening
I also have a Xiaomi AIoT AC2350 router and I'm trying to connect via SSH to upload the Padavan software. I tried to start by connecting through the DAP-1635 extedner but I don't know what I'm doing wrong because it still doesn't work. Can I count on a more detailed instruction what to do?

**Comment by eisaev** [comment]
@dobosz23, I am not sure that this discussion is appropriate here, because the methods that I will describe cannot be implemented in OpenWRTInvasion, because they require physical manipulation. I suggest moving the discussion of methods to a topic on the OpenWRT forum: https://forum.openwrt.org/t/support-aiot-ac2350-xiaomi/70451/26

**Comment by dobosz23** [comment]
Of course, thank you for the quick reply

**Comment by dobosz23** [comment]
I run on the firmware 1.3.8 CN an succesfully open SSH connection:
https://forum.openwrt.org/uploads/default/original/3X/0/5/052424e33141929b074afdf4bab9328eb8020c07.png

**Comment by eisaev** [comment]
> I run on the firmware 1.3.8 CN an succesfully open SSH connection:
> 
> ![](https://camo.githubusercontent.com/27dcbc38d6c00cad44115334056c6d326dfdd43a7d1fab2577c0a3525f4bae6a/68747470733a2f2f666f72756d2e6f70656e7772742e6f72672f75706c6f6164732f64656661756c742f6f726967696e616c2f33582f302f352f303532343234653333313431393239623037346166646634626162393332386562383032306330372e706e67)
> 
> I run command as root and connect not a: ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc -o UserKnownHostsFile=/dev/null root@192.168.0.171 but: ssh root@192.168.0.171

It was a mistake. SSH access was obtained by a different method.  Reproducing using OpenWRTInvasion failed:
https://forum.openwrt.org/t/support-aiot-ac2350-xiaomi/70451/86
