### ISSUE TITLE
xiaomi r3gv2 report errors

### ISSUE THREAD

**Issue by 778154145** [acecilia/OpenWRTInvasion#47]
python remote_command_execution_vulnerability.py
After executing the command
Traceback (most recent call last):
  File "remote_command_execution_vulnerability.py", line 42, in <module>
    template = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

**Comment by acecilia** [comment]
I cant help much with that information you provided
