### ISSUE TITLE
an UnicodeEncodeError on my environment

### ISSUE THREAD

**Issue by keke1023** [acecilia/OpenWRTInvasion#48]
Traceback (most recent call last):
  File "remote_command_execution_vulnerability.py", line 42, in <module>
    template = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

Traceback (most recent call last):
  File "remote_command_execution_vulnerability.py", line 46, in <module>
    f.write(data)
UnicodeEncodeError: 'gbk' codec can't encode character '\ufeff' in position 0: illegal multibyte sequence

and i add encoding='UTF-8' to open(), it works

speed_test_filename = "speedtest_urls.xml"
with open("speedtest_urls_template.xml", "rt", encoding='UTF-8') as f:
    template = f.read()
data = template.format(router_ip_address=router_ip_address, command=command)
with open("build/speedtest_urls.xml", 'wt', encoding='UTF-8') as f:
    f.write(data)

**Comment by acecilia** [comment]
Related: https://github.com/acecilia/OpenWRTInvasion/issues/47

Thanks! Could you please open a Pull Request with the change? 🙏

**Comment by acecilia** [comment]
Fixed

**Comment by keke1023** [comment]
@acecilia sorry i havent notice notification of your reply,thanks for fix it ,have a good day
