### ISSUE TITLE
vulnerability had been fixed 

### ISSUE THREAD

**Issue by xsser** [acecilia/OpenWRTInvasion#51]
version:
小米路由器4A千兆版(R4A) | MiWiFi 稳定版 2.28.65 |  

response:
```

No page is registered at '/web/home/api/misystem/c_upload'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
```

<img width="1378" alt="图片" src="https://user-images.githubusercontent.com/1850771/101352939-d224a480-38cd-11eb-9448-c283d89dcb25.png">

**Comment by Zarto** [comment]
Hi ! Not sure your problem is related to mine (I had no errors, just the Telnet server not responding), but I had to use the OpenWRTInvasion version 0.0.1 because the last version was failing.  Version 0.0.1 worked fine.

**Comment by acecilia** [comment]
I cant really provide any help here as the issue is not explained properly. Please refer to the Readme, the setup is explained in great detail
