### ISSUE TITLE
Can't opkg update after install / Connectivity issues

### ISSUE THREAD

**Issue by derkomai** [acecilia/OpenWRTInvasion#52]
I've just installed the OpenWrt/06-06-2020 snapshot in a Xiaomi Router 4A Gigabit edition. The installation seems to complete OK, and I connected the Xiaomi router to my Asus main router, but I can only SSH into the Xiaomi router directly through a cable, not through other computers on the network. Also, once I've ssh'd into it , I can ping, for example, 8.8.8.8, but I can't use opkg to update or to install luci. I get these errors:

```
Downloading http://downloads.openwrt.org/snapshots/targets/ramips/mt7621/packages/Packages.gz
Failed to establish connection
*** Failed to download the package list from http://downloads.openwrt.org/snapshots/targets/ramips/mt7621/packages/Packages.gz
```

Note: I had to `uci set network.wan.dns="1.1.1.1"` to be able to have connectivity on the laptop that is directly connected to the Xiaomi router. For some reason the Xiaomi router didn't get the dns from the main router. And, despite having Internet connection on the laptop connected to the Xiaomi, I can't update/install luci on the Xiaomi from ssh.

**Comment by acecilia** [comment]
This seems like a network problem related to your particular setup, and not an issue on OpenWRTInvasion. Please refer to the OpenWrt forums for support, or try to change your network setup to a simpler one.
