### ISSUE TITLE
Openvpn-Openssl Package

### ISSUE THREAD

**Issue by hyper2009m** [acecilia/OpenWRTInvasion#57]
Hi,

I want to install Openvpn-Openssl but i get Kernel: Version Incompatible.
(I am attaching you image)

Is anywhere for this version of Kernel or i have to wait for an update?
![f6edfddf1bdf28c741793e3ff76280af353f5691_2_666x500](https://user-images.githubusercontent.com/76633776/103341994-09cbda00-4a91-11eb-904f-5fcee112b565.jpeg)
Regards

**Comment by acecilia** [comment]
Cant help, I do not currently use OpenWrt in my xiaomi router. Try asking in the OpenWrt forum 🙂
