### ISSUE TITLE
After flashing, the LAN port is closed by default, what should I do next? 

### ISSUE THREAD

**Issue by tl-Tangliang** [acecilia/OpenWRTInvasion#6]
I followed your steps to find the firmware of the appropriate model. After flashing, the LAN port is closed by default. What should I do next? , now I have a computer with Internet access, a router, two network cables, and a Xiaomi router

**Comment by acecilia** [comment]
As you can imagine, I can not help you because you did not provide any information about what your problem is. Please post in the OpenWrt forum and read the readme of this repo
