### ISSUE TITLE
R4AC can not telnet

### ISSUE THREAD

**Issue by zhzhyu** [acecilia/OpenWRTInvasion#60]
![微信截图_20210114164638](https://user-images.githubusercontent.com/58381672/104566273-5fef6e80-5688-11eb-86d8-ae5c330f381d.jpg)
![微信截图_20210114164259](https://user-images.githubusercontent.com/58381672/104566279-61b93200-5688-11eb-83d0-40a1ffae6182.jpg)

**Comment by zhzhyu** [comment]
I don't know why I can't successful

**Comment by zhzhyu** [comment]
I had try 0.0.1,also can't

**Comment by acecilia** [comment]
I don’t know either. Please read the readme or read other issues in this repository. Most of the problems come from a complex network configuration, try to simplify it

**Comment by d1y** [comment]
> I had try 0.0.1,also can't

老铁, 你成功了吗, 我也是这样, 几个版本都是试过了, 都不行

ssh 和 telnet

**Comment by latel** [comment]
yout English is very funny
