### ISSUE TITLE
R3L cannot working

### ISSUE THREAD

**Issue by LiarOnce** [acecilia/OpenWRTInvasion#61]
Firmware is `2.9.217` but I also tried `2.14.45`.
0.0.1:
The `netcat` has no output.
![2021-01-16_23-31](https://user-images.githubusercontent.com/11171892/104816057-962d1980-5853-11eb-8e50-65ff289f3f5f.png)
0.0.6:
Error in telnet connection: Connection refused.
![2021-01-16_23-31_1](https://user-images.githubusercontent.com/11171892/104816165-3be08880-5854-11eb-9014-941a6c167357.png)

**Comment by alberto0o** [comment]
Same problem with xiomi mi 3C, i have been looking and maybe some url is not working inside the script, maybe the urls from speedtest... I dont know hehe didnt check much, but i have same issue as you

**Comment by LiarOnce** [comment]
I got an error: `{"code":1629,"msg":"unzip error, file is not intack"}` 
And it has nothing to do with the network environment:
![2021-01-17_10-04](https://user-images.githubusercontent.com/11171892/104829172-14b5a580-58ac-11eb-8f59-fef40a2871c7.png)

**Comment by LiarOnce** [comment]
Now it's working https://github.com/acecilia/OpenWRTInvasion/issues/62#issuecomment-761727533
