### ISSUE TITLE
[Xiaomi 4A Gigabit] Dead link to OpenWrt snapshot

### ISSUE THREAD

**Issue by PinkyAcorn** [acecilia/OpenWRTInvasion#64]
Dead (outdated?) link to the latest OpenWrt snapshot
https://github.com/acecilia/OpenWRTInvasion#install-openwrt

I use link from OpenWrt wiki (https://openwrt.org/inbox/toh/xiaomi/xiaomi_mi_router_4a_gigabit_edition) with success 
https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin

**Comment by acecilia** [comment]
Readme updated, thanks!
