### ISSUE TITLE
how to back stock firmware

### ISSUE THREAD

**Issue by emresenyuva** [acecilia/OpenWRTInvasion#66]
what am I do for to back to stock firmware?

**Comment by acecilia** [comment]
Try reading and finding the information online

**Comment by mrwiwi** [comment]
Seriously ? Wow... Can't find any info on how to, maybe it's as simple as updated from luci ? Or maybe not, not a single line on how to ! Please answer...

**Comment by acecilia** [comment]
I dont know all answers. In order to answer this I will need to search for such information online. So please try to do it yourself instead, and if you find the answer post it here for others to see

**Comment by acecilia** [comment]
@mrwiwi I am happy to accept a pull request
