### ISSUE TITLE
luci not starting

### ISSUE THREAD

**Issue by paoletto** [acecilia/OpenWRTInvasion#67]
Hi, i tried to install luci in the currently linked image( `https://raw.githubusercontent.com/acecilia/OpenWRTInvasion/master/firmwares/OpenWrt/06-06-2020/openwrt-ramips-mt7621-xiaomi_mir3g-v2-squashfs-sysupgrade.bin` ), with
opkg update; opkg install luci
That gives an error:
check_data_file_clashes: Package libnl-tiny1 wants to install file /usr/lib/libnl-tiny.so But that file is already provided by package  * libnl-tiny

so i went on and tried with --force-overwrite.
That worked, but then uhttpd wouldn't start and i was getting connection refused.

googling i found:
opkg  --force-reinstall install uhttpd

This got me a responding web server on port 80, but the result is "bad gateway"

logread reports:
```Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: /usr/bin/lua: /usr/lib/lua/luci/util.lua:669: Unable to establish ubus connection
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: stack traceback:
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	[C]: in function 'assert'
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	/usr/lib/lua/luci/util.lua:669: in function </usr/lib/lua/luci/util.lua:666>
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	(tail call): ?
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	/usr/lib/lua/luci/model/uci.lua:322: in function 'get_all'
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	/usr/lib/lua/luci/config.lua:12: in function </usr/lib/lua/luci/config.lua:10>
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	/usr/lib/lua/luci/cacheloader.lua:10: in main chunk
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	[C]: in function 'require'
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	/www/cgi-bin/luci:2: in main chunk
Sun Feb 21 00:23:55 2021 daemon.err uhttpd[2405]: 	[C]: ?
```

**Comment by acecilia** [comment]
I cant really give much support on this, as there is no stable version of OpenWrt. I think the firmware you tried to use is outdated, I did update the [readme](https://github.com/acecilia/OpenWRTInvasion#install-openwrt) some weeks ago with more updated links:

> One of the images listed in the official OpenWrt wiki page
