### ISSUE TITLE
Nothing Starts After Running The Script

### ISSUE THREAD

**Issue by ahamza61** [acecilia/OpenWRTInvasion#7]
Nothing happens after step 2.

`Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\system32> cd d:/1
PS D:\1> pip3 install -r requirements.txt # Install requirements
Requirement already satisfied: pycrypto in c:\program files\python39\lib\site-packages\pycrypto-2.6.1-py3.9-win-amd64.egg (from -r requirements.txt (line 1)) (2.6.1)
PS D:\1> python3 remote_command_execution_vulnerability.py # Run the script
PS D:\1>`

**Comment by acecilia** [comment]
As you can imagine, I can not help you because you did not provide any information about what your problem is. Please post in the OpenWrt forum and read the readme of this repo
