### ISSUE TITLE
not an issue: just reporting working on c4 v2.14.87 and a4 v2.18.62 directly

### ISSUE THREAD

**Issue by AddaxSoft** [acecilia/OpenWRTInvasion#73]
tested with internet-less version. works smoothly.

**Comment by acecilia** [comment]
Thanks! Added to the readme

**Comment by jeodai** [comment]
Unfortunate, I just tested failed on C4 v2.14.87. Are you share? I used the tag 0.0.1 version

**Comment by zhining-lu** [comment]
I test sucess on C4 v2.14.87, used the tag 0.0.10 version

**Comment by ming0070913** [comment]
[Edited]
Test sucess on 4C v2.14.87 with tag 0.0.10 version
Had to use normal mode instead of repeater mode and run invasion on Mac

**Comment by silentidiot** [comment]
can anyone help me flash openwrt? i have v2.14.87 mi router 4c and encountered this error
![image](https://github.com/acecilia/OpenWRTInvasion/assets/172534171/5f790bc9-7b3b-4492-9362-762a7f0c0617)

**Comment by peiyingyao** [comment]
> can anyone help me flash openwrt? i have v2.14.87 mi router 4c and encountered this error ![image](https://private-user-images.githubusercontent.com/172534171/339088191-5f790bc9-7b3b-4492-9362-762a7f0c0617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjIwMTUsIm5iZiI6MTczMjk2MTcxNSwicGF0aCI6Ii8xNzI1MzQxNzEvMzM5MDg4MTkxLTVmNzkwYmM5LTdiM2ItNDQ5Mi05MzYyLTc2MmE3ZjBjMDYxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMDE1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzhhMzkzNmRlYmI2NzQ5YzU1ODI1OGFhMGQ1ODA1Zjc4NThlMjkwZmY3YzdhYWFiMjE3MjM5NDUwMGU1NzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UO-cN00vmjZMB5qoRxdgwRReSl76IxS0GFpLgW_EJLU)

Temporarily allow Python.exe in the firewall to accept inbound connections
