### ISSUE TITLE
website http://dl.ijinshan.com/safe/speedtest/ not avaiable

### ISSUE THREAD

**Issue by ralf-neugebauer** [acecilia/OpenWRTInvasion#90]
Hello,

The website http://dl.ijinshan.com/safe/speedtest/ is not accessible.
So the script is not wotking.
What can I do to free the Xiaomi?

Kind regards
 Ralf

**Comment by acecilia** [comment]
No idea :/ I do not know what the `http://dl.ijinshan.com/safe/speedtest/` url is about

**Comment by ralf-neugebauer** [comment]
Hello,

This URLs are from the speedtest_urls_template.xml.
I tried your program with the version 0.1 and higher on two different Xiaomi´s but I had no luck  for unlock them.
So I just testetd and found this URLs not accessible.

Kind regards
 Ralf
