### ISSUE TITLE
not working on mi router 4q

### ISSUE THREAD

**Issue by flower756** [acecilia/OpenWRTInvasion#91]
i used the 0.0.1 version,started a netcat process,and the output was all fine.But when i tried to use the telnet connection,it said "正在连接192.168.31.1...无法打开到主机的连接。 在端口 23: 连接失败"(connecting to 192.168.31.1...cannot open the connection to the host machine.On port 23:connecting failed),so what can i do?(i tried to run this script for 10 times,but not working at all,and also tried to unplug and plug the power to do a manual restart,but still not working)

**Comment by acecilia** [comment]
Simplify your network configuration, read the rest of the issues on this repository and try again
