### ISSUE TITLE
ssh: connect to host 192.168.31.1 port 22: Connection refused

### ISSUE THREAD

**Issue by zhouchangming0727** [acecilia/OpenWRTInvasion#96]
start uploading config file...
start exec command...
done! Now you can connect to the router using several options: (user: root, password: root)
* telnet 192.168.31.1
* ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc -o UserKnownHostsFile=/dev/null root@192.168.31.1
* ftp: using a program like cyberduck

**Comment by zhouchangming0727** [comment]
sorry   my python version problem

**Comment by a751565522** [comment]
我也有这个问题  所以是python版本太高了还是太低了的原因  ？

**Comment by OliverParoczai** [comment]
Agreed, using Python 3.10 fixed it
